name: test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [ main ] }

jobs:
  test-providers:
    if: ${{ !(github.event.pull_request.draft || false) }}
    strategy:
      fail-fast: false
      matrix:
        provider:
          - vapor/jwt
          - vapor/fluent
          - vapor/leaf
          - vapor/queues
          - vapor/apns
        include:
          - ref: main
          - provider: vapor/apns
            ref: 3.0.0
    runs-on: ubuntu-latest
    container: swift:5.8-jammy
    steps: 
      - name: Check out Vapor
        uses: actions/checkout@v3
        with:
          path: vapor
      - name: Check out provider
        uses: actions/checkout@v3
        with: 
          repository: ${{ matrix.provider }}
          path: provider
          ref: ${{ matrix.ref }}
      - name: Use local Vapor
        run: swift package --package-path ./provider edit vapor --path ./vapor
      - name: Run tests
        env:
            SWIFT_DETERMINISTIC_HASHING: 1
        run: swift test --package-path ./provider

  unit-tests:
     uses: vapor/ci/.github/workflows/run-unit-tests.yml@reusable-workflows
     with:
       with_coverage: true
       with_tsan: false
       with_public_api_check: true
